# Generated by Django 4.0.4 on 2022-05-12 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_sale_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=200)),
                ('is_product', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
            options={
                'verbose_name': 'ProductService',
                'verbose_name_plural': 'ProductServices',
            },
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='operation_data',
            new_name='operation_date',
        ),
        migrations.CreateModel(
            name='SaleProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('quantity', models.IntegerField()),
                ('product_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marketplace.productservice')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marketplace.sale')),
            ],
            options={
                'verbose_name': 'SaleProductService',
                'verbose_name_plural': 'SaleProductServices',
            },
        ),
    ]
