# Generated by Django 4.0.4 on 2022-05-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rename_productservice_productactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproductactivity',
            name='product_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_activity', to='marketplace.productactivity'),
        ),
        migrations.AlterField(
            model_name='saleproductactivity',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='marketplace.sale'),
        ),
    ]
