# Generated by Django 4.0.4 on 2022-05-15 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_remove_saleproductactivity_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productactivity',
            name='commission',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(0)]),
        ),
    ]
